spring:
  profiles:
    active: dev

cloud.aws:
  region.static: ap-northeast-2
  stack.auto: true

---
spring:
  profiles: dev
  application:
    name: Kms-test-pjt
  redis:
    port: 6379
    host: 127.0.0.1

cloud:
  aws:
    credentials:
      profile-name: dev
    stack.auto: false

